Div sqrt
sequencer/arithmetic pull request #37
Opened 2023-10-26 05:06 UTC by midnighter95

Add square root design.

Add DivSqrt Module in FP32 and its test.

2023-10-26 05:27 UTC, sequencer requested changes

2023-10-26 05:27 UTC, sequencer commented on .gitmodules
> +	url = git@github.com:ucb-bar/berkeley-softfloat-3.git
@Avimitin can we use nix here?

2023-10-26 05:27 UTC, sequencer commented on tests/src/Tester.scala
> +package tests
Move to `build.sc`, see T1/build.sc

2023-10-26 05:27 UTC, sequencer commented on tests/resources/includes/verilator.h
> +class VerilatedVcdFILE : public VerilatedVcdFile {
Use FST

2023-10-26 05:27 UTC, sequencer commented on tests/resources/csrc/vbridge_impl.h
> +class VBridgeImpl {
VBridge???

2023-10-26 05:27 UTC, sequencer commented on tests/resources/csrc/vbridge_impl.cc
> +std::vector<testdata> mygen_az_f32(float32_t trueFunction(float32_t),
name...

2023-10-26 05:27 UTC, sequencer commented on tests/resources/csrc/vbridge_impl.cc
> +}
no need timeout check

2023-10-26 05:27 UTC, sequencer commented on common.sc
>  // TODO: migrate test to svsim
remove this todo

2023-10-26 05:27 UTC, sequencer commented on arithmetic/src/sqrt/QDS.scala
> +          ),
why defining this uop?

2023-10-26 05:27 UTC, sequencer commented on arithmetic/src/sqrt/QDS.scala
> +  // from P269 in <Digital Arithmetic> : /16， should have got from SRTTable.
TODO: calculate this table

2023-10-26 05:27 UTC, sequencer commented on arithmetic/src/float/RoundingUnit.scala
> +  val rmRMM = (input.roundingMode === RoundingMode.RMM)
decode out

2023-11-02 13:43 UTC, cyyself approved these changes
F32_DIV and SQRT with different rounding mode works. LGTM.

2023-11-06 06:35 UTC, sequencer requested changes

2023-11-06 06:35 UTC, sequencer commented on build.sc
> +  ).call(os.pwd).out.text.trim()
use env

2023-11-06 08:58 UTC, sequencer approved these changes

2023-11-06 08:58 UTC, merged